package com.syou.emedia.server.mapper.app;

import com.syou.emedia.server.model.app.PFAppPromote;
import com.syou.emedia.server.model.app.PFAppPromoteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PFAppPromoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_promote
     *
     * @mbggenerated
     */
    int countByExample(PFAppPromoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_promote
     *
     * @mbggenerated
     */
    int deleteByExample(PFAppPromoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_promote
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer appId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_promote
     *
     * @mbggenerated
     */
    int insert(PFAppPromote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_promote
     *
     * @mbggenerated
     */
    int insertSelective(PFAppPromote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_promote
     *
     * @mbggenerated
     */
    List<PFAppPromote> selectByExampleWithRowbounds(PFAppPromoteExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_promote
     *
     * @mbggenerated
     */
    List<PFAppPromote> selectByExample(PFAppPromoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_promote
     *
     * @mbggenerated
     */
    PFAppPromote selectByPrimaryKey(Integer appId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_promote
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PFAppPromote record, @Param("example") PFAppPromoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_promote
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PFAppPromote record, @Param("example") PFAppPromoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_promote
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PFAppPromote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_promote
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PFAppPromote record);
}