package com.syou.emedia.server.mapper.app;

import com.syou.emedia.server.model.app.PFCodeMapping;
import com.syou.emedia.server.model.app.PFCodeMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PFCodeMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_code_mapping
     *
     * @mbggenerated
     */
    int countByExample(PFCodeMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_code_mapping
     *
     * @mbggenerated
     */
    int deleteByExample(PFCodeMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_code_mapping
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer codeMappingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_code_mapping
     *
     * @mbggenerated
     */
    int insert(PFCodeMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_code_mapping
     *
     * @mbggenerated
     */
    int insertSelective(PFCodeMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_code_mapping
     *
     * @mbggenerated
     */
    List<PFCodeMapping> selectByExampleWithRowbounds(PFCodeMappingExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_code_mapping
     *
     * @mbggenerated
     */
    List<PFCodeMapping> selectByExample(PFCodeMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_code_mapping
     *
     * @mbggenerated
     */
    PFCodeMapping selectByPrimaryKey(Integer codeMappingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_code_mapping
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PFCodeMapping record, @Param("example") PFCodeMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_code_mapping
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PFCodeMapping record, @Param("example") PFCodeMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_code_mapping
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PFCodeMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_code_mapping
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PFCodeMapping record);
}