package com.syou.emedia.server.model.log;

import java.util.Date;

public class PFLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.log_id
     *
     * @mbggenerated
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.tran_id
     *
     * @mbggenerated
     */
    private String tranId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.key_id
     *
     * @mbggenerated
     */
    private String keyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.key_value
     *
     * @mbggenerated
     */
    private String keyValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.intf_name
     *
     * @mbggenerated
     */
    private String intfName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.version_code
     *
     * @mbggenerated
     */
    private String versionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.req_obj
     *
     * @mbggenerated
     */
    private String reqObj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.rsp_obj
     *
     * @mbggenerated
     */
    private String rspObj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.encrypt_req_obj
     *
     * @mbggenerated
     */
    private String encryptReqObj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.encrypt_rsp_obj
     *
     * @mbggenerated
     */
    private String encryptRspObj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.costs_time
     *
     * @mbggenerated
     */
    private Integer costsTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.state_code
     *
     * @mbggenerated
     */
    private String stateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_log.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.log_id
     *
     * @return the value of platform_log.log_id
     *
     * @mbggenerated
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.log_id
     *
     * @param logId the value for platform_log.log_id
     *
     * @mbggenerated
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.app_id
     *
     * @return the value of platform_log.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.app_id
     *
     * @param appId the value for platform_log.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.tran_id
     *
     * @return the value of platform_log.tran_id
     *
     * @mbggenerated
     */
    public String getTranId() {
        return tranId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.tran_id
     *
     * @param tranId the value for platform_log.tran_id
     *
     * @mbggenerated
     */
    public void setTranId(String tranId) {
        this.tranId = tranId == null ? null : tranId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.token
     *
     * @return the value of platform_log.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.token
     *
     * @param token the value for platform_log.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.key_id
     *
     * @return the value of platform_log.key_id
     *
     * @mbggenerated
     */
    public String getKeyId() {
        return keyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.key_id
     *
     * @param keyId the value for platform_log.key_id
     *
     * @mbggenerated
     */
    public void setKeyId(String keyId) {
        this.keyId = keyId == null ? null : keyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.key_value
     *
     * @return the value of platform_log.key_value
     *
     * @mbggenerated
     */
    public String getKeyValue() {
        return keyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.key_value
     *
     * @param keyValue the value for platform_log.key_value
     *
     * @mbggenerated
     */
    public void setKeyValue(String keyValue) {
        this.keyValue = keyValue == null ? null : keyValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.intf_name
     *
     * @return the value of platform_log.intf_name
     *
     * @mbggenerated
     */
    public String getIntfName() {
        return intfName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.intf_name
     *
     * @param intfName the value for platform_log.intf_name
     *
     * @mbggenerated
     */
    public void setIntfName(String intfName) {
        this.intfName = intfName == null ? null : intfName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.version_code
     *
     * @return the value of platform_log.version_code
     *
     * @mbggenerated
     */
    public String getVersionCode() {
        return versionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.version_code
     *
     * @param versionCode the value for platform_log.version_code
     *
     * @mbggenerated
     */
    public void setVersionCode(String versionCode) {
        this.versionCode = versionCode == null ? null : versionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.req_obj
     *
     * @return the value of platform_log.req_obj
     *
     * @mbggenerated
     */
    public String getReqObj() {
        return reqObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.req_obj
     *
     * @param reqObj the value for platform_log.req_obj
     *
     * @mbggenerated
     */
    public void setReqObj(String reqObj) {
        this.reqObj = reqObj == null ? null : reqObj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.rsp_obj
     *
     * @return the value of platform_log.rsp_obj
     *
     * @mbggenerated
     */
    public String getRspObj() {
        return rspObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.rsp_obj
     *
     * @param rspObj the value for platform_log.rsp_obj
     *
     * @mbggenerated
     */
    public void setRspObj(String rspObj) {
        this.rspObj = rspObj == null ? null : rspObj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.encrypt_req_obj
     *
     * @return the value of platform_log.encrypt_req_obj
     *
     * @mbggenerated
     */
    public String getEncryptReqObj() {
        return encryptReqObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.encrypt_req_obj
     *
     * @param encryptReqObj the value for platform_log.encrypt_req_obj
     *
     * @mbggenerated
     */
    public void setEncryptReqObj(String encryptReqObj) {
        this.encryptReqObj = encryptReqObj == null ? null : encryptReqObj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.encrypt_rsp_obj
     *
     * @return the value of platform_log.encrypt_rsp_obj
     *
     * @mbggenerated
     */
    public String getEncryptRspObj() {
        return encryptRspObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.encrypt_rsp_obj
     *
     * @param encryptRspObj the value for platform_log.encrypt_rsp_obj
     *
     * @mbggenerated
     */
    public void setEncryptRspObj(String encryptRspObj) {
        this.encryptRspObj = encryptRspObj == null ? null : encryptRspObj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.costs_time
     *
     * @return the value of platform_log.costs_time
     *
     * @mbggenerated
     */
    public Integer getCostsTime() {
        return costsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.costs_time
     *
     * @param costsTime the value for platform_log.costs_time
     *
     * @mbggenerated
     */
    public void setCostsTime(Integer costsTime) {
        this.costsTime = costsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.state_code
     *
     * @return the value of platform_log.state_code
     *
     * @mbggenerated
     */
    public String getStateCode() {
        return stateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.state_code
     *
     * @param stateCode the value for platform_log.state_code
     *
     * @mbggenerated
     */
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode == null ? null : stateCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.message
     *
     * @return the value of platform_log.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.message
     *
     * @param message the value for platform_log.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.create_time
     *
     * @return the value of platform_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.create_time
     *
     * @param createTime the value for platform_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_log.remark
     *
     * @return the value of platform_log.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_log.remark
     *
     * @param remark the value for platform_log.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logId=").append(logId);
        sb.append(", appId=").append(appId);
        sb.append(", tranId=").append(tranId);
        sb.append(", token=").append(token);
        sb.append(", keyId=").append(keyId);
        sb.append(", keyValue=").append(keyValue);
        sb.append(", intfName=").append(intfName);
        sb.append(", versionCode=").append(versionCode);
        sb.append(", reqObj=").append(reqObj);
        sb.append(", rspObj=").append(rspObj);
        sb.append(", encryptReqObj=").append(encryptReqObj);
        sb.append(", encryptRspObj=").append(encryptRspObj);
        sb.append(", costsTime=").append(costsTime);
        sb.append(", stateCode=").append(stateCode);
        sb.append(", message=").append(message);
        sb.append(", createTime=").append(createTime);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}