package com.syou.emedia.server.model.log;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PFLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    public PFLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLogIdIsNull() {
            addCriterion("log_id is null");
            return (Criteria) this;
        }

        public Criteria andLogIdIsNotNull() {
            addCriterion("log_id is not null");
            return (Criteria) this;
        }

        public Criteria andLogIdEqualTo(Integer value) {
            addCriterion("log_id =", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotEqualTo(Integer value) {
            addCriterion("log_id <>", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdGreaterThan(Integer value) {
            addCriterion("log_id >", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("log_id >=", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdLessThan(Integer value) {
            addCriterion("log_id <", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdLessThanOrEqualTo(Integer value) {
            addCriterion("log_id <=", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdIn(List<Integer> values) {
            addCriterion("log_id in", values, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotIn(List<Integer> values) {
            addCriterion("log_id not in", values, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdBetween(Integer value1, Integer value2) {
            addCriterion("log_id between", value1, value2, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotBetween(Integer value1, Integer value2) {
            addCriterion("log_id not between", value1, value2, "logId");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("app_id like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("app_id not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andTranIdIsNull() {
            addCriterion("tran_id is null");
            return (Criteria) this;
        }

        public Criteria andTranIdIsNotNull() {
            addCriterion("tran_id is not null");
            return (Criteria) this;
        }

        public Criteria andTranIdEqualTo(String value) {
            addCriterion("tran_id =", value, "tranId");
            return (Criteria) this;
        }

        public Criteria andTranIdNotEqualTo(String value) {
            addCriterion("tran_id <>", value, "tranId");
            return (Criteria) this;
        }

        public Criteria andTranIdGreaterThan(String value) {
            addCriterion("tran_id >", value, "tranId");
            return (Criteria) this;
        }

        public Criteria andTranIdGreaterThanOrEqualTo(String value) {
            addCriterion("tran_id >=", value, "tranId");
            return (Criteria) this;
        }

        public Criteria andTranIdLessThan(String value) {
            addCriterion("tran_id <", value, "tranId");
            return (Criteria) this;
        }

        public Criteria andTranIdLessThanOrEqualTo(String value) {
            addCriterion("tran_id <=", value, "tranId");
            return (Criteria) this;
        }

        public Criteria andTranIdLike(String value) {
            addCriterion("tran_id like", value, "tranId");
            return (Criteria) this;
        }

        public Criteria andTranIdNotLike(String value) {
            addCriterion("tran_id not like", value, "tranId");
            return (Criteria) this;
        }

        public Criteria andTranIdIn(List<String> values) {
            addCriterion("tran_id in", values, "tranId");
            return (Criteria) this;
        }

        public Criteria andTranIdNotIn(List<String> values) {
            addCriterion("tran_id not in", values, "tranId");
            return (Criteria) this;
        }

        public Criteria andTranIdBetween(String value1, String value2) {
            addCriterion("tran_id between", value1, value2, "tranId");
            return (Criteria) this;
        }

        public Criteria andTranIdNotBetween(String value1, String value2) {
            addCriterion("tran_id not between", value1, value2, "tranId");
            return (Criteria) this;
        }

        public Criteria andTokenIsNull() {
            addCriterion("token is null");
            return (Criteria) this;
        }

        public Criteria andTokenIsNotNull() {
            addCriterion("token is not null");
            return (Criteria) this;
        }

        public Criteria andTokenEqualTo(String value) {
            addCriterion("token =", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotEqualTo(String value) {
            addCriterion("token <>", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThan(String value) {
            addCriterion("token >", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThanOrEqualTo(String value) {
            addCriterion("token >=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThan(String value) {
            addCriterion("token <", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThanOrEqualTo(String value) {
            addCriterion("token <=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLike(String value) {
            addCriterion("token like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotLike(String value) {
            addCriterion("token not like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenIn(List<String> values) {
            addCriterion("token in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotIn(List<String> values) {
            addCriterion("token not in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenBetween(String value1, String value2) {
            addCriterion("token between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotBetween(String value1, String value2) {
            addCriterion("token not between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andKeyIdIsNull() {
            addCriterion("key_id is null");
            return (Criteria) this;
        }

        public Criteria andKeyIdIsNotNull() {
            addCriterion("key_id is not null");
            return (Criteria) this;
        }

        public Criteria andKeyIdEqualTo(String value) {
            addCriterion("key_id =", value, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdNotEqualTo(String value) {
            addCriterion("key_id <>", value, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdGreaterThan(String value) {
            addCriterion("key_id >", value, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdGreaterThanOrEqualTo(String value) {
            addCriterion("key_id >=", value, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdLessThan(String value) {
            addCriterion("key_id <", value, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdLessThanOrEqualTo(String value) {
            addCriterion("key_id <=", value, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdLike(String value) {
            addCriterion("key_id like", value, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdNotLike(String value) {
            addCriterion("key_id not like", value, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdIn(List<String> values) {
            addCriterion("key_id in", values, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdNotIn(List<String> values) {
            addCriterion("key_id not in", values, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdBetween(String value1, String value2) {
            addCriterion("key_id between", value1, value2, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyIdNotBetween(String value1, String value2) {
            addCriterion("key_id not between", value1, value2, "keyId");
            return (Criteria) this;
        }

        public Criteria andKeyValueIsNull() {
            addCriterion("key_value is null");
            return (Criteria) this;
        }

        public Criteria andKeyValueIsNotNull() {
            addCriterion("key_value is not null");
            return (Criteria) this;
        }

        public Criteria andKeyValueEqualTo(String value) {
            addCriterion("key_value =", value, "keyValue");
            return (Criteria) this;
        }

        public Criteria andKeyValueNotEqualTo(String value) {
            addCriterion("key_value <>", value, "keyValue");
            return (Criteria) this;
        }

        public Criteria andKeyValueGreaterThan(String value) {
            addCriterion("key_value >", value, "keyValue");
            return (Criteria) this;
        }

        public Criteria andKeyValueGreaterThanOrEqualTo(String value) {
            addCriterion("key_value >=", value, "keyValue");
            return (Criteria) this;
        }

        public Criteria andKeyValueLessThan(String value) {
            addCriterion("key_value <", value, "keyValue");
            return (Criteria) this;
        }

        public Criteria andKeyValueLessThanOrEqualTo(String value) {
            addCriterion("key_value <=", value, "keyValue");
            return (Criteria) this;
        }

        public Criteria andKeyValueLike(String value) {
            addCriterion("key_value like", value, "keyValue");
            return (Criteria) this;
        }

        public Criteria andKeyValueNotLike(String value) {
            addCriterion("key_value not like", value, "keyValue");
            return (Criteria) this;
        }

        public Criteria andKeyValueIn(List<String> values) {
            addCriterion("key_value in", values, "keyValue");
            return (Criteria) this;
        }

        public Criteria andKeyValueNotIn(List<String> values) {
            addCriterion("key_value not in", values, "keyValue");
            return (Criteria) this;
        }

        public Criteria andKeyValueBetween(String value1, String value2) {
            addCriterion("key_value between", value1, value2, "keyValue");
            return (Criteria) this;
        }

        public Criteria andKeyValueNotBetween(String value1, String value2) {
            addCriterion("key_value not between", value1, value2, "keyValue");
            return (Criteria) this;
        }

        public Criteria andIntfNameIsNull() {
            addCriterion("intf_name is null");
            return (Criteria) this;
        }

        public Criteria andIntfNameIsNotNull() {
            addCriterion("intf_name is not null");
            return (Criteria) this;
        }

        public Criteria andIntfNameEqualTo(String value) {
            addCriterion("intf_name =", value, "intfName");
            return (Criteria) this;
        }

        public Criteria andIntfNameNotEqualTo(String value) {
            addCriterion("intf_name <>", value, "intfName");
            return (Criteria) this;
        }

        public Criteria andIntfNameGreaterThan(String value) {
            addCriterion("intf_name >", value, "intfName");
            return (Criteria) this;
        }

        public Criteria andIntfNameGreaterThanOrEqualTo(String value) {
            addCriterion("intf_name >=", value, "intfName");
            return (Criteria) this;
        }

        public Criteria andIntfNameLessThan(String value) {
            addCriterion("intf_name <", value, "intfName");
            return (Criteria) this;
        }

        public Criteria andIntfNameLessThanOrEqualTo(String value) {
            addCriterion("intf_name <=", value, "intfName");
            return (Criteria) this;
        }

        public Criteria andIntfNameLike(String value) {
            addCriterion("intf_name like", value, "intfName");
            return (Criteria) this;
        }

        public Criteria andIntfNameNotLike(String value) {
            addCriterion("intf_name not like", value, "intfName");
            return (Criteria) this;
        }

        public Criteria andIntfNameIn(List<String> values) {
            addCriterion("intf_name in", values, "intfName");
            return (Criteria) this;
        }

        public Criteria andIntfNameNotIn(List<String> values) {
            addCriterion("intf_name not in", values, "intfName");
            return (Criteria) this;
        }

        public Criteria andIntfNameBetween(String value1, String value2) {
            addCriterion("intf_name between", value1, value2, "intfName");
            return (Criteria) this;
        }

        public Criteria andIntfNameNotBetween(String value1, String value2) {
            addCriterion("intf_name not between", value1, value2, "intfName");
            return (Criteria) this;
        }

        public Criteria andVersionCodeIsNull() {
            addCriterion("version_code is null");
            return (Criteria) this;
        }

        public Criteria andVersionCodeIsNotNull() {
            addCriterion("version_code is not null");
            return (Criteria) this;
        }

        public Criteria andVersionCodeEqualTo(String value) {
            addCriterion("version_code =", value, "versionCode");
            return (Criteria) this;
        }

        public Criteria andVersionCodeNotEqualTo(String value) {
            addCriterion("version_code <>", value, "versionCode");
            return (Criteria) this;
        }

        public Criteria andVersionCodeGreaterThan(String value) {
            addCriterion("version_code >", value, "versionCode");
            return (Criteria) this;
        }

        public Criteria andVersionCodeGreaterThanOrEqualTo(String value) {
            addCriterion("version_code >=", value, "versionCode");
            return (Criteria) this;
        }

        public Criteria andVersionCodeLessThan(String value) {
            addCriterion("version_code <", value, "versionCode");
            return (Criteria) this;
        }

        public Criteria andVersionCodeLessThanOrEqualTo(String value) {
            addCriterion("version_code <=", value, "versionCode");
            return (Criteria) this;
        }

        public Criteria andVersionCodeLike(String value) {
            addCriterion("version_code like", value, "versionCode");
            return (Criteria) this;
        }

        public Criteria andVersionCodeNotLike(String value) {
            addCriterion("version_code not like", value, "versionCode");
            return (Criteria) this;
        }

        public Criteria andVersionCodeIn(List<String> values) {
            addCriterion("version_code in", values, "versionCode");
            return (Criteria) this;
        }

        public Criteria andVersionCodeNotIn(List<String> values) {
            addCriterion("version_code not in", values, "versionCode");
            return (Criteria) this;
        }

        public Criteria andVersionCodeBetween(String value1, String value2) {
            addCriterion("version_code between", value1, value2, "versionCode");
            return (Criteria) this;
        }

        public Criteria andVersionCodeNotBetween(String value1, String value2) {
            addCriterion("version_code not between", value1, value2, "versionCode");
            return (Criteria) this;
        }

        public Criteria andReqObjIsNull() {
            addCriterion("req_obj is null");
            return (Criteria) this;
        }

        public Criteria andReqObjIsNotNull() {
            addCriterion("req_obj is not null");
            return (Criteria) this;
        }

        public Criteria andReqObjEqualTo(String value) {
            addCriterion("req_obj =", value, "reqObj");
            return (Criteria) this;
        }

        public Criteria andReqObjNotEqualTo(String value) {
            addCriterion("req_obj <>", value, "reqObj");
            return (Criteria) this;
        }

        public Criteria andReqObjGreaterThan(String value) {
            addCriterion("req_obj >", value, "reqObj");
            return (Criteria) this;
        }

        public Criteria andReqObjGreaterThanOrEqualTo(String value) {
            addCriterion("req_obj >=", value, "reqObj");
            return (Criteria) this;
        }

        public Criteria andReqObjLessThan(String value) {
            addCriterion("req_obj <", value, "reqObj");
            return (Criteria) this;
        }

        public Criteria andReqObjLessThanOrEqualTo(String value) {
            addCriterion("req_obj <=", value, "reqObj");
            return (Criteria) this;
        }

        public Criteria andReqObjLike(String value) {
            addCriterion("req_obj like", value, "reqObj");
            return (Criteria) this;
        }

        public Criteria andReqObjNotLike(String value) {
            addCriterion("req_obj not like", value, "reqObj");
            return (Criteria) this;
        }

        public Criteria andReqObjIn(List<String> values) {
            addCriterion("req_obj in", values, "reqObj");
            return (Criteria) this;
        }

        public Criteria andReqObjNotIn(List<String> values) {
            addCriterion("req_obj not in", values, "reqObj");
            return (Criteria) this;
        }

        public Criteria andReqObjBetween(String value1, String value2) {
            addCriterion("req_obj between", value1, value2, "reqObj");
            return (Criteria) this;
        }

        public Criteria andReqObjNotBetween(String value1, String value2) {
            addCriterion("req_obj not between", value1, value2, "reqObj");
            return (Criteria) this;
        }

        public Criteria andRspObjIsNull() {
            addCriterion("rsp_obj is null");
            return (Criteria) this;
        }

        public Criteria andRspObjIsNotNull() {
            addCriterion("rsp_obj is not null");
            return (Criteria) this;
        }

        public Criteria andRspObjEqualTo(String value) {
            addCriterion("rsp_obj =", value, "rspObj");
            return (Criteria) this;
        }

        public Criteria andRspObjNotEqualTo(String value) {
            addCriterion("rsp_obj <>", value, "rspObj");
            return (Criteria) this;
        }

        public Criteria andRspObjGreaterThan(String value) {
            addCriterion("rsp_obj >", value, "rspObj");
            return (Criteria) this;
        }

        public Criteria andRspObjGreaterThanOrEqualTo(String value) {
            addCriterion("rsp_obj >=", value, "rspObj");
            return (Criteria) this;
        }

        public Criteria andRspObjLessThan(String value) {
            addCriterion("rsp_obj <", value, "rspObj");
            return (Criteria) this;
        }

        public Criteria andRspObjLessThanOrEqualTo(String value) {
            addCriterion("rsp_obj <=", value, "rspObj");
            return (Criteria) this;
        }

        public Criteria andRspObjLike(String value) {
            addCriterion("rsp_obj like", value, "rspObj");
            return (Criteria) this;
        }

        public Criteria andRspObjNotLike(String value) {
            addCriterion("rsp_obj not like", value, "rspObj");
            return (Criteria) this;
        }

        public Criteria andRspObjIn(List<String> values) {
            addCriterion("rsp_obj in", values, "rspObj");
            return (Criteria) this;
        }

        public Criteria andRspObjNotIn(List<String> values) {
            addCriterion("rsp_obj not in", values, "rspObj");
            return (Criteria) this;
        }

        public Criteria andRspObjBetween(String value1, String value2) {
            addCriterion("rsp_obj between", value1, value2, "rspObj");
            return (Criteria) this;
        }

        public Criteria andRspObjNotBetween(String value1, String value2) {
            addCriterion("rsp_obj not between", value1, value2, "rspObj");
            return (Criteria) this;
        }

        public Criteria andEncryptReqObjIsNull() {
            addCriterion("encrypt_req_obj is null");
            return (Criteria) this;
        }

        public Criteria andEncryptReqObjIsNotNull() {
            addCriterion("encrypt_req_obj is not null");
            return (Criteria) this;
        }

        public Criteria andEncryptReqObjEqualTo(String value) {
            addCriterion("encrypt_req_obj =", value, "encryptReqObj");
            return (Criteria) this;
        }

        public Criteria andEncryptReqObjNotEqualTo(String value) {
            addCriterion("encrypt_req_obj <>", value, "encryptReqObj");
            return (Criteria) this;
        }

        public Criteria andEncryptReqObjGreaterThan(String value) {
            addCriterion("encrypt_req_obj >", value, "encryptReqObj");
            return (Criteria) this;
        }

        public Criteria andEncryptReqObjGreaterThanOrEqualTo(String value) {
            addCriterion("encrypt_req_obj >=", value, "encryptReqObj");
            return (Criteria) this;
        }

        public Criteria andEncryptReqObjLessThan(String value) {
            addCriterion("encrypt_req_obj <", value, "encryptReqObj");
            return (Criteria) this;
        }

        public Criteria andEncryptReqObjLessThanOrEqualTo(String value) {
            addCriterion("encrypt_req_obj <=", value, "encryptReqObj");
            return (Criteria) this;
        }

        public Criteria andEncryptReqObjLike(String value) {
            addCriterion("encrypt_req_obj like", value, "encryptReqObj");
            return (Criteria) this;
        }

        public Criteria andEncryptReqObjNotLike(String value) {
            addCriterion("encrypt_req_obj not like", value, "encryptReqObj");
            return (Criteria) this;
        }

        public Criteria andEncryptReqObjIn(List<String> values) {
            addCriterion("encrypt_req_obj in", values, "encryptReqObj");
            return (Criteria) this;
        }

        public Criteria andEncryptReqObjNotIn(List<String> values) {
            addCriterion("encrypt_req_obj not in", values, "encryptReqObj");
            return (Criteria) this;
        }

        public Criteria andEncryptReqObjBetween(String value1, String value2) {
            addCriterion("encrypt_req_obj between", value1, value2, "encryptReqObj");
            return (Criteria) this;
        }

        public Criteria andEncryptReqObjNotBetween(String value1, String value2) {
            addCriterion("encrypt_req_obj not between", value1, value2, "encryptReqObj");
            return (Criteria) this;
        }

        public Criteria andEncryptRspObjIsNull() {
            addCriterion("encrypt_rsp_obj is null");
            return (Criteria) this;
        }

        public Criteria andEncryptRspObjIsNotNull() {
            addCriterion("encrypt_rsp_obj is not null");
            return (Criteria) this;
        }

        public Criteria andEncryptRspObjEqualTo(String value) {
            addCriterion("encrypt_rsp_obj =", value, "encryptRspObj");
            return (Criteria) this;
        }

        public Criteria andEncryptRspObjNotEqualTo(String value) {
            addCriterion("encrypt_rsp_obj <>", value, "encryptRspObj");
            return (Criteria) this;
        }

        public Criteria andEncryptRspObjGreaterThan(String value) {
            addCriterion("encrypt_rsp_obj >", value, "encryptRspObj");
            return (Criteria) this;
        }

        public Criteria andEncryptRspObjGreaterThanOrEqualTo(String value) {
            addCriterion("encrypt_rsp_obj >=", value, "encryptRspObj");
            return (Criteria) this;
        }

        public Criteria andEncryptRspObjLessThan(String value) {
            addCriterion("encrypt_rsp_obj <", value, "encryptRspObj");
            return (Criteria) this;
        }

        public Criteria andEncryptRspObjLessThanOrEqualTo(String value) {
            addCriterion("encrypt_rsp_obj <=", value, "encryptRspObj");
            return (Criteria) this;
        }

        public Criteria andEncryptRspObjLike(String value) {
            addCriterion("encrypt_rsp_obj like", value, "encryptRspObj");
            return (Criteria) this;
        }

        public Criteria andEncryptRspObjNotLike(String value) {
            addCriterion("encrypt_rsp_obj not like", value, "encryptRspObj");
            return (Criteria) this;
        }

        public Criteria andEncryptRspObjIn(List<String> values) {
            addCriterion("encrypt_rsp_obj in", values, "encryptRspObj");
            return (Criteria) this;
        }

        public Criteria andEncryptRspObjNotIn(List<String> values) {
            addCriterion("encrypt_rsp_obj not in", values, "encryptRspObj");
            return (Criteria) this;
        }

        public Criteria andEncryptRspObjBetween(String value1, String value2) {
            addCriterion("encrypt_rsp_obj between", value1, value2, "encryptRspObj");
            return (Criteria) this;
        }

        public Criteria andEncryptRspObjNotBetween(String value1, String value2) {
            addCriterion("encrypt_rsp_obj not between", value1, value2, "encryptRspObj");
            return (Criteria) this;
        }

        public Criteria andCostsTimeIsNull() {
            addCriterion("costs_time is null");
            return (Criteria) this;
        }

        public Criteria andCostsTimeIsNotNull() {
            addCriterion("costs_time is not null");
            return (Criteria) this;
        }

        public Criteria andCostsTimeEqualTo(Integer value) {
            addCriterion("costs_time =", value, "costsTime");
            return (Criteria) this;
        }

        public Criteria andCostsTimeNotEqualTo(Integer value) {
            addCriterion("costs_time <>", value, "costsTime");
            return (Criteria) this;
        }

        public Criteria andCostsTimeGreaterThan(Integer value) {
            addCriterion("costs_time >", value, "costsTime");
            return (Criteria) this;
        }

        public Criteria andCostsTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("costs_time >=", value, "costsTime");
            return (Criteria) this;
        }

        public Criteria andCostsTimeLessThan(Integer value) {
            addCriterion("costs_time <", value, "costsTime");
            return (Criteria) this;
        }

        public Criteria andCostsTimeLessThanOrEqualTo(Integer value) {
            addCriterion("costs_time <=", value, "costsTime");
            return (Criteria) this;
        }

        public Criteria andCostsTimeIn(List<Integer> values) {
            addCriterion("costs_time in", values, "costsTime");
            return (Criteria) this;
        }

        public Criteria andCostsTimeNotIn(List<Integer> values) {
            addCriterion("costs_time not in", values, "costsTime");
            return (Criteria) this;
        }

        public Criteria andCostsTimeBetween(Integer value1, Integer value2) {
            addCriterion("costs_time between", value1, value2, "costsTime");
            return (Criteria) this;
        }

        public Criteria andCostsTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("costs_time not between", value1, value2, "costsTime");
            return (Criteria) this;
        }

        public Criteria andStateCodeIsNull() {
            addCriterion("state_code is null");
            return (Criteria) this;
        }

        public Criteria andStateCodeIsNotNull() {
            addCriterion("state_code is not null");
            return (Criteria) this;
        }

        public Criteria andStateCodeEqualTo(String value) {
            addCriterion("state_code =", value, "stateCode");
            return (Criteria) this;
        }

        public Criteria andStateCodeNotEqualTo(String value) {
            addCriterion("state_code <>", value, "stateCode");
            return (Criteria) this;
        }

        public Criteria andStateCodeGreaterThan(String value) {
            addCriterion("state_code >", value, "stateCode");
            return (Criteria) this;
        }

        public Criteria andStateCodeGreaterThanOrEqualTo(String value) {
            addCriterion("state_code >=", value, "stateCode");
            return (Criteria) this;
        }

        public Criteria andStateCodeLessThan(String value) {
            addCriterion("state_code <", value, "stateCode");
            return (Criteria) this;
        }

        public Criteria andStateCodeLessThanOrEqualTo(String value) {
            addCriterion("state_code <=", value, "stateCode");
            return (Criteria) this;
        }

        public Criteria andStateCodeLike(String value) {
            addCriterion("state_code like", value, "stateCode");
            return (Criteria) this;
        }

        public Criteria andStateCodeNotLike(String value) {
            addCriterion("state_code not like", value, "stateCode");
            return (Criteria) this;
        }

        public Criteria andStateCodeIn(List<String> values) {
            addCriterion("state_code in", values, "stateCode");
            return (Criteria) this;
        }

        public Criteria andStateCodeNotIn(List<String> values) {
            addCriterion("state_code not in", values, "stateCode");
            return (Criteria) this;
        }

        public Criteria andStateCodeBetween(String value1, String value2) {
            addCriterion("state_code between", value1, value2, "stateCode");
            return (Criteria) this;
        }

        public Criteria andStateCodeNotBetween(String value1, String value2) {
            addCriterion("state_code not between", value1, value2, "stateCode");
            return (Criteria) this;
        }

        public Criteria andMessageIsNull() {
            addCriterion("message is null");
            return (Criteria) this;
        }

        public Criteria andMessageIsNotNull() {
            addCriterion("message is not null");
            return (Criteria) this;
        }

        public Criteria andMessageEqualTo(String value) {
            addCriterion("message =", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotEqualTo(String value) {
            addCriterion("message <>", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThan(String value) {
            addCriterion("message >", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThanOrEqualTo(String value) {
            addCriterion("message >=", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLessThan(String value) {
            addCriterion("message <", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLessThanOrEqualTo(String value) {
            addCriterion("message <=", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLike(String value) {
            addCriterion("message like", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotLike(String value) {
            addCriterion("message not like", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageIn(List<String> values) {
            addCriterion("message in", values, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotIn(List<String> values) {
            addCriterion("message not in", values, "message");
            return (Criteria) this;
        }

        public Criteria andMessageBetween(String value1, String value2) {
            addCriterion("message between", value1, value2, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotBetween(String value1, String value2) {
            addCriterion("message not between", value1, value2, "message");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table platform_log
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}