package com.syou.emedia.server.model.coupon;

import java.util.Date;

public class PFCoupon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_coupon.coupon_id
     *
     * @mbggenerated
     */
    private Integer couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_coupon.channel_id
     *
     * @mbggenerated
     */
    private Integer channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_coupon.apply_order_id
     *
     * @mbggenerated
     */
    private String applyOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_coupon.out_coupon_id
     *
     * @mbggenerated
     */
    private String outCouponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_coupon.out_coupon_code
     *
     * @mbggenerated
     */
    private String outCouponCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_coupon.out_coupon_type
     *
     * @mbggenerated
     */
    private String outCouponType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_coupon.out_coupon_amount
     *
     * @mbggenerated
     */
    private String outCouponAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_coupon.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_coupon.coupon_id
     *
     * @return the value of platform_coupon.coupon_id
     *
     * @mbggenerated
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_coupon.coupon_id
     *
     * @param couponId the value for platform_coupon.coupon_id
     *
     * @mbggenerated
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_coupon.channel_id
     *
     * @return the value of platform_coupon.channel_id
     *
     * @mbggenerated
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_coupon.channel_id
     *
     * @param channelId the value for platform_coupon.channel_id
     *
     * @mbggenerated
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_coupon.apply_order_id
     *
     * @return the value of platform_coupon.apply_order_id
     *
     * @mbggenerated
     */
    public String getApplyOrderId() {
        return applyOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_coupon.apply_order_id
     *
     * @param applyOrderId the value for platform_coupon.apply_order_id
     *
     * @mbggenerated
     */
    public void setApplyOrderId(String applyOrderId) {
        this.applyOrderId = applyOrderId == null ? null : applyOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_coupon.out_coupon_id
     *
     * @return the value of platform_coupon.out_coupon_id
     *
     * @mbggenerated
     */
    public String getOutCouponId() {
        return outCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_coupon.out_coupon_id
     *
     * @param outCouponId the value for platform_coupon.out_coupon_id
     *
     * @mbggenerated
     */
    public void setOutCouponId(String outCouponId) {
        this.outCouponId = outCouponId == null ? null : outCouponId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_coupon.out_coupon_code
     *
     * @return the value of platform_coupon.out_coupon_code
     *
     * @mbggenerated
     */
    public String getOutCouponCode() {
        return outCouponCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_coupon.out_coupon_code
     *
     * @param outCouponCode the value for platform_coupon.out_coupon_code
     *
     * @mbggenerated
     */
    public void setOutCouponCode(String outCouponCode) {
        this.outCouponCode = outCouponCode == null ? null : outCouponCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_coupon.out_coupon_type
     *
     * @return the value of platform_coupon.out_coupon_type
     *
     * @mbggenerated
     */
    public String getOutCouponType() {
        return outCouponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_coupon.out_coupon_type
     *
     * @param outCouponType the value for platform_coupon.out_coupon_type
     *
     * @mbggenerated
     */
    public void setOutCouponType(String outCouponType) {
        this.outCouponType = outCouponType == null ? null : outCouponType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_coupon.out_coupon_amount
     *
     * @return the value of platform_coupon.out_coupon_amount
     *
     * @mbggenerated
     */
    public String getOutCouponAmount() {
        return outCouponAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_coupon.out_coupon_amount
     *
     * @param outCouponAmount the value for platform_coupon.out_coupon_amount
     *
     * @mbggenerated
     */
    public void setOutCouponAmount(String outCouponAmount) {
        this.outCouponAmount = outCouponAmount == null ? null : outCouponAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_coupon.create_time
     *
     * @return the value of platform_coupon.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_coupon.create_time
     *
     * @param createTime the value for platform_coupon.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_coupon
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", couponId=").append(couponId);
        sb.append(", channelId=").append(channelId);
        sb.append(", applyOrderId=").append(applyOrderId);
        sb.append(", outCouponId=").append(outCouponId);
        sb.append(", outCouponCode=").append(outCouponCode);
        sb.append(", outCouponType=").append(outCouponType);
        sb.append(", outCouponAmount=").append(outCouponAmount);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}