package com.syou.emedia.server.mapper.attr;

import com.syou.emedia.server.model.attr.PFAttr;
import com.syou.emedia.server.model.attr.PFAttrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PFAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_attr
     *
     * @mbggenerated
     */
    int countByExample(PFAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_attr
     *
     * @mbggenerated
     */
    int deleteByExample(PFAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_attr
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer attrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_attr
     *
     * @mbggenerated
     */
    int insert(PFAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_attr
     *
     * @mbggenerated
     */
    int insertSelective(PFAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_attr
     *
     * @mbggenerated
     */
    List<PFAttr> selectByExampleWithRowbounds(PFAttrExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_attr
     *
     * @mbggenerated
     */
    List<PFAttr> selectByExample(PFAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_attr
     *
     * @mbggenerated
     */
    PFAttr selectByPrimaryKey(Integer attrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_attr
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PFAttr record, @Param("example") PFAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_attr
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PFAttr record, @Param("example") PFAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_attr
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PFAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_attr
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PFAttr record);
}