package com.syou.emedia.server.model.commodity;

import java.util.Date;

public class PFCommodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_commodity.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_commodity.commodity_type_id
     *
     * @mbggenerated
     */
    private Integer commodityTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_commodity.ext_commodity_id
     *
     * @mbggenerated
     */
    private String extCommodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_commodity.channel_id
     *
     * @mbggenerated
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_commodity.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_commodity.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_commodity.commodity_id
     *
     * @return the value of platform_commodity.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_commodity.commodity_id
     *
     * @param commodityId the value for platform_commodity.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_commodity.commodity_type_id
     *
     * @return the value of platform_commodity.commodity_type_id
     *
     * @mbggenerated
     */
    public Integer getCommodityTypeId() {
        return commodityTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_commodity.commodity_type_id
     *
     * @param commodityTypeId the value for platform_commodity.commodity_type_id
     *
     * @mbggenerated
     */
    public void setCommodityTypeId(Integer commodityTypeId) {
        this.commodityTypeId = commodityTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_commodity.ext_commodity_id
     *
     * @return the value of platform_commodity.ext_commodity_id
     *
     * @mbggenerated
     */
    public String getExtCommodityId() {
        return extCommodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_commodity.ext_commodity_id
     *
     * @param extCommodityId the value for platform_commodity.ext_commodity_id
     *
     * @mbggenerated
     */
    public void setExtCommodityId(String extCommodityId) {
        this.extCommodityId = extCommodityId == null ? null : extCommodityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_commodity.channel_id
     *
     * @return the value of platform_commodity.channel_id
     *
     * @mbggenerated
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_commodity.channel_id
     *
     * @param channelId the value for platform_commodity.channel_id
     *
     * @mbggenerated
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_commodity.create_time
     *
     * @return the value of platform_commodity.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_commodity.create_time
     *
     * @param createTime the value for platform_commodity.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_commodity.status
     *
     * @return the value of platform_commodity.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_commodity.status
     *
     * @param status the value for platform_commodity.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_commodity
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", commodityId=").append(commodityId);
        sb.append(", commodityTypeId=").append(commodityTypeId);
        sb.append(", extCommodityId=").append(extCommodityId);
        sb.append(", channelId=").append(channelId);
        sb.append(", createTime=").append(createTime);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}