package com.syou.emedia.server.mapper.coupon;

import com.syou.emedia.server.model.coupon.PFCoupon;
import com.syou.emedia.server.model.coupon.PFCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PFCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_coupon
     *
     * @mbggenerated
     */
    int countByExample(PFCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_coupon
     *
     * @mbggenerated
     */
    int deleteByExample(PFCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_coupon
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_coupon
     *
     * @mbggenerated
     */
    int insert(PFCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_coupon
     *
     * @mbggenerated
     */
    int insertSelective(PFCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_coupon
     *
     * @mbggenerated
     */
    List<PFCoupon> selectByExampleWithRowbounds(PFCouponExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_coupon
     *
     * @mbggenerated
     */
    List<PFCoupon> selectByExample(PFCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_coupon
     *
     * @mbggenerated
     */
    PFCoupon selectByPrimaryKey(Integer couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_coupon
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PFCoupon record, @Param("example") PFCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_coupon
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PFCoupon record, @Param("example") PFCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PFCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PFCoupon record);
}