package com.syou.emedia.server.mapper.commodity;

import com.syou.emedia.server.model.commodity.PFCommodityType;
import com.syou.emedia.server.model.commodity.PFCommodityTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PFCommodityTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_commodity_type
     *
     * @mbggenerated
     */
    int countByExample(PFCommodityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_commodity_type
     *
     * @mbggenerated
     */
    int deleteByExample(PFCommodityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_commodity_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer commodityTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_commodity_type
     *
     * @mbggenerated
     */
    int insert(PFCommodityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_commodity_type
     *
     * @mbggenerated
     */
    int insertSelective(PFCommodityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_commodity_type
     *
     * @mbggenerated
     */
    List<PFCommodityType> selectByExampleWithRowbounds(PFCommodityTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_commodity_type
     *
     * @mbggenerated
     */
    List<PFCommodityType> selectByExample(PFCommodityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_commodity_type
     *
     * @mbggenerated
     */
    PFCommodityType selectByPrimaryKey(Integer commodityTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_commodity_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PFCommodityType record, @Param("example") PFCommodityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_commodity_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PFCommodityType record, @Param("example") PFCommodityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_commodity_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PFCommodityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_commodity_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PFCommodityType record);
}