package com.syou.emedia.server.model.app;

import java.util.Date;

public class PFAppPromote {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_app_promote.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_app_promote.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_app_promote.ico_url
     *
     * @mbggenerated
     */
    private String icoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_app_promote.download_url
     *
     * @mbggenerated
     */
    private String downloadUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_app_promote.ext_app_code
     *
     * @mbggenerated
     */
    private String extAppCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_app_promote.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_app_promote.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_app_promote.app_id
     *
     * @return the value of platform_app_promote.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_app_promote.app_id
     *
     * @param appId the value for platform_app_promote.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_app_promote.app_name
     *
     * @return the value of platform_app_promote.app_name
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_app_promote.app_name
     *
     * @param appName the value for platform_app_promote.app_name
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_app_promote.ico_url
     *
     * @return the value of platform_app_promote.ico_url
     *
     * @mbggenerated
     */
    public String getIcoUrl() {
        return icoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_app_promote.ico_url
     *
     * @param icoUrl the value for platform_app_promote.ico_url
     *
     * @mbggenerated
     */
    public void setIcoUrl(String icoUrl) {
        this.icoUrl = icoUrl == null ? null : icoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_app_promote.download_url
     *
     * @return the value of platform_app_promote.download_url
     *
     * @mbggenerated
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_app_promote.download_url
     *
     * @param downloadUrl the value for platform_app_promote.download_url
     *
     * @mbggenerated
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl == null ? null : downloadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_app_promote.ext_app_code
     *
     * @return the value of platform_app_promote.ext_app_code
     *
     * @mbggenerated
     */
    public String getExtAppCode() {
        return extAppCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_app_promote.ext_app_code
     *
     * @param extAppCode the value for platform_app_promote.ext_app_code
     *
     * @mbggenerated
     */
    public void setExtAppCode(String extAppCode) {
        this.extAppCode = extAppCode == null ? null : extAppCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_app_promote.status
     *
     * @return the value of platform_app_promote.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_app_promote.status
     *
     * @param status the value for platform_app_promote.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_app_promote.create_time
     *
     * @return the value of platform_app_promote.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_app_promote.create_time
     *
     * @param createTime the value for platform_app_promote.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_promote
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", appId=").append(appId);
        sb.append(", appName=").append(appName);
        sb.append(", icoUrl=").append(icoUrl);
        sb.append(", downloadUrl=").append(downloadUrl);
        sb.append(", extAppCode=").append(extAppCode);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}