package com.syou.emedia.server.model.app;

import java.util.Date;

public class PFCodeMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_code_mapping.code_mapping_id
     *
     * @mbggenerated
     */
    private Integer codeMappingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_code_mapping.code_mapping_type
     *
     * @mbggenerated
     */
    private String codeMappingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_code_mapping.code_a_id
     *
     * @mbggenerated
     */
    private String codeAId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_code_mapping.code_a_value
     *
     * @mbggenerated
     */
    private String codeAValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_code_mapping.code_a_code
     *
     * @mbggenerated
     */
    private String codeACode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_code_mapping.code_z_id
     *
     * @mbggenerated
     */
    private String codeZId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_code_mapping.code_z_value
     *
     * @mbggenerated
     */
    private String codeZValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_code_mapping.code_z_code
     *
     * @mbggenerated
     */
    private String codeZCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_code_mapping.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_code_mapping.status_cd
     *
     * @mbggenerated
     */
    private String statusCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_code_mapping.status_time
     *
     * @mbggenerated
     */
    private Date statusTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_code_mapping.code_mapping_id
     *
     * @return the value of platform_code_mapping.code_mapping_id
     *
     * @mbggenerated
     */
    public Integer getCodeMappingId() {
        return codeMappingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_code_mapping.code_mapping_id
     *
     * @param codeMappingId the value for platform_code_mapping.code_mapping_id
     *
     * @mbggenerated
     */
    public void setCodeMappingId(Integer codeMappingId) {
        this.codeMappingId = codeMappingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_code_mapping.code_mapping_type
     *
     * @return the value of platform_code_mapping.code_mapping_type
     *
     * @mbggenerated
     */
    public String getCodeMappingType() {
        return codeMappingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_code_mapping.code_mapping_type
     *
     * @param codeMappingType the value for platform_code_mapping.code_mapping_type
     *
     * @mbggenerated
     */
    public void setCodeMappingType(String codeMappingType) {
        this.codeMappingType = codeMappingType == null ? null : codeMappingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_code_mapping.code_a_id
     *
     * @return the value of platform_code_mapping.code_a_id
     *
     * @mbggenerated
     */
    public String getCodeAId() {
        return codeAId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_code_mapping.code_a_id
     *
     * @param codeAId the value for platform_code_mapping.code_a_id
     *
     * @mbggenerated
     */
    public void setCodeAId(String codeAId) {
        this.codeAId = codeAId == null ? null : codeAId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_code_mapping.code_a_value
     *
     * @return the value of platform_code_mapping.code_a_value
     *
     * @mbggenerated
     */
    public String getCodeAValue() {
        return codeAValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_code_mapping.code_a_value
     *
     * @param codeAValue the value for platform_code_mapping.code_a_value
     *
     * @mbggenerated
     */
    public void setCodeAValue(String codeAValue) {
        this.codeAValue = codeAValue == null ? null : codeAValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_code_mapping.code_a_code
     *
     * @return the value of platform_code_mapping.code_a_code
     *
     * @mbggenerated
     */
    public String getCodeACode() {
        return codeACode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_code_mapping.code_a_code
     *
     * @param codeACode the value for platform_code_mapping.code_a_code
     *
     * @mbggenerated
     */
    public void setCodeACode(String codeACode) {
        this.codeACode = codeACode == null ? null : codeACode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_code_mapping.code_z_id
     *
     * @return the value of platform_code_mapping.code_z_id
     *
     * @mbggenerated
     */
    public String getCodeZId() {
        return codeZId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_code_mapping.code_z_id
     *
     * @param codeZId the value for platform_code_mapping.code_z_id
     *
     * @mbggenerated
     */
    public void setCodeZId(String codeZId) {
        this.codeZId = codeZId == null ? null : codeZId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_code_mapping.code_z_value
     *
     * @return the value of platform_code_mapping.code_z_value
     *
     * @mbggenerated
     */
    public String getCodeZValue() {
        return codeZValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_code_mapping.code_z_value
     *
     * @param codeZValue the value for platform_code_mapping.code_z_value
     *
     * @mbggenerated
     */
    public void setCodeZValue(String codeZValue) {
        this.codeZValue = codeZValue == null ? null : codeZValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_code_mapping.code_z_code
     *
     * @return the value of platform_code_mapping.code_z_code
     *
     * @mbggenerated
     */
    public String getCodeZCode() {
        return codeZCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_code_mapping.code_z_code
     *
     * @param codeZCode the value for platform_code_mapping.code_z_code
     *
     * @mbggenerated
     */
    public void setCodeZCode(String codeZCode) {
        this.codeZCode = codeZCode == null ? null : codeZCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_code_mapping.create_time
     *
     * @return the value of platform_code_mapping.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_code_mapping.create_time
     *
     * @param createTime the value for platform_code_mapping.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_code_mapping.status_cd
     *
     * @return the value of platform_code_mapping.status_cd
     *
     * @mbggenerated
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_code_mapping.status_cd
     *
     * @param statusCd the value for platform_code_mapping.status_cd
     *
     * @mbggenerated
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd == null ? null : statusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_code_mapping.status_time
     *
     * @return the value of platform_code_mapping.status_time
     *
     * @mbggenerated
     */
    public Date getStatusTime() {
        return statusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_code_mapping.status_time
     *
     * @param statusTime the value for platform_code_mapping.status_time
     *
     * @mbggenerated
     */
    public void setStatusTime(Date statusTime) {
        this.statusTime = statusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_code_mapping
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", codeMappingId=").append(codeMappingId);
        sb.append(", codeMappingType=").append(codeMappingType);
        sb.append(", codeAId=").append(codeAId);
        sb.append(", codeAValue=").append(codeAValue);
        sb.append(", codeACode=").append(codeACode);
        sb.append(", codeZId=").append(codeZId);
        sb.append(", codeZValue=").append(codeZValue);
        sb.append(", codeZCode=").append(codeZCode);
        sb.append(", createTime=").append(createTime);
        sb.append(", statusCd=").append(statusCd);
        sb.append(", statusTime=").append(statusTime);
        sb.append("]");
        return sb.toString();
    }
}