package com.syou.emedia.server.mapper.system;

import com.syou.emedia.server.model.system.PFSystem;
import com.syou.emedia.server.model.system.PFSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PFSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    int countByExample(PFSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    int deleteByExample(PFSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer systemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    int insert(PFSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    int insertSelective(PFSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    List<PFSystem> selectByExampleWithRowbounds(PFSystemExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    List<PFSystem> selectByExample(PFSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    PFSystem selectByPrimaryKey(Integer systemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PFSystem record, @Param("example") PFSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PFSystem record, @Param("example") PFSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PFSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PFSystem record);
}