package com.syou.emedia.server.mapper.terminal;

import com.syou.emedia.server.model.terminal.PFTerminal;
import com.syou.emedia.server.model.terminal.PFTerminalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PFTerminalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_terminal
     *
     * @mbggenerated
     */
    int countByExample(PFTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_terminal
     *
     * @mbggenerated
     */
    int deleteByExample(PFTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_terminal
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer terminalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_terminal
     *
     * @mbggenerated
     */
    int insert(PFTerminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_terminal
     *
     * @mbggenerated
     */
    int insertSelective(PFTerminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_terminal
     *
     * @mbggenerated
     */
    List<PFTerminal> selectByExampleWithRowbounds(PFTerminalExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_terminal
     *
     * @mbggenerated
     */
    List<PFTerminal> selectByExample(PFTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_terminal
     *
     * @mbggenerated
     */
    PFTerminal selectByPrimaryKey(Integer terminalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_terminal
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PFTerminal record, @Param("example") PFTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_terminal
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PFTerminal record, @Param("example") PFTerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_terminal
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PFTerminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_terminal
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PFTerminal record);
}