package com.syou.emedia.server.model.system;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PFSystemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    public PFSystemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSystemIdIsNull() {
            addCriterion("system_id is null");
            return (Criteria) this;
        }

        public Criteria andSystemIdIsNotNull() {
            addCriterion("system_id is not null");
            return (Criteria) this;
        }

        public Criteria andSystemIdEqualTo(Integer value) {
            addCriterion("system_id =", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotEqualTo(Integer value) {
            addCriterion("system_id <>", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdGreaterThan(Integer value) {
            addCriterion("system_id >", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("system_id >=", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdLessThan(Integer value) {
            addCriterion("system_id <", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdLessThanOrEqualTo(Integer value) {
            addCriterion("system_id <=", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdIn(List<Integer> values) {
            addCriterion("system_id in", values, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotIn(List<Integer> values) {
            addCriterion("system_id not in", values, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdBetween(Integer value1, Integer value2) {
            addCriterion("system_id between", value1, value2, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("system_id not between", value1, value2, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemNameIsNull() {
            addCriterion("system_name is null");
            return (Criteria) this;
        }

        public Criteria andSystemNameIsNotNull() {
            addCriterion("system_name is not null");
            return (Criteria) this;
        }

        public Criteria andSystemNameEqualTo(String value) {
            addCriterion("system_name =", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotEqualTo(String value) {
            addCriterion("system_name <>", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameGreaterThan(String value) {
            addCriterion("system_name >", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameGreaterThanOrEqualTo(String value) {
            addCriterion("system_name >=", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameLessThan(String value) {
            addCriterion("system_name <", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameLessThanOrEqualTo(String value) {
            addCriterion("system_name <=", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameLike(String value) {
            addCriterion("system_name like", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotLike(String value) {
            addCriterion("system_name not like", value, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameIn(List<String> values) {
            addCriterion("system_name in", values, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotIn(List<String> values) {
            addCriterion("system_name not in", values, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameBetween(String value1, String value2) {
            addCriterion("system_name between", value1, value2, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemNameNotBetween(String value1, String value2) {
            addCriterion("system_name not between", value1, value2, "systemName");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIsNull() {
            addCriterion("system_code is null");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIsNotNull() {
            addCriterion("system_code is not null");
            return (Criteria) this;
        }

        public Criteria andSystemCodeEqualTo(String value) {
            addCriterion("system_code =", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotEqualTo(String value) {
            addCriterion("system_code <>", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeGreaterThan(String value) {
            addCriterion("system_code >", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeGreaterThanOrEqualTo(String value) {
            addCriterion("system_code >=", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLessThan(String value) {
            addCriterion("system_code <", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLessThanOrEqualTo(String value) {
            addCriterion("system_code <=", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeLike(String value) {
            addCriterion("system_code like", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotLike(String value) {
            addCriterion("system_code not like", value, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeIn(List<String> values) {
            addCriterion("system_code in", values, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotIn(List<String> values) {
            addCriterion("system_code not in", values, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeBetween(String value1, String value2) {
            addCriterion("system_code between", value1, value2, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemCodeNotBetween(String value1, String value2) {
            addCriterion("system_code not between", value1, value2, "systemCode");
            return (Criteria) this;
        }

        public Criteria andSystemLevelIsNull() {
            addCriterion("system_level is null");
            return (Criteria) this;
        }

        public Criteria andSystemLevelIsNotNull() {
            addCriterion("system_level is not null");
            return (Criteria) this;
        }

        public Criteria andSystemLevelEqualTo(String value) {
            addCriterion("system_level =", value, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelNotEqualTo(String value) {
            addCriterion("system_level <>", value, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelGreaterThan(String value) {
            addCriterion("system_level >", value, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelGreaterThanOrEqualTo(String value) {
            addCriterion("system_level >=", value, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelLessThan(String value) {
            addCriterion("system_level <", value, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelLessThanOrEqualTo(String value) {
            addCriterion("system_level <=", value, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelLike(String value) {
            addCriterion("system_level like", value, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelNotLike(String value) {
            addCriterion("system_level not like", value, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelIn(List<String> values) {
            addCriterion("system_level in", values, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelNotIn(List<String> values) {
            addCriterion("system_level not in", values, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelBetween(String value1, String value2) {
            addCriterion("system_level between", value1, value2, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemLevelNotBetween(String value1, String value2) {
            addCriterion("system_level not between", value1, value2, "systemLevel");
            return (Criteria) this;
        }

        public Criteria andSystemTypeIsNull() {
            addCriterion("system_type is null");
            return (Criteria) this;
        }

        public Criteria andSystemTypeIsNotNull() {
            addCriterion("system_type is not null");
            return (Criteria) this;
        }

        public Criteria andSystemTypeEqualTo(String value) {
            addCriterion("system_type =", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeNotEqualTo(String value) {
            addCriterion("system_type <>", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeGreaterThan(String value) {
            addCriterion("system_type >", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeGreaterThanOrEqualTo(String value) {
            addCriterion("system_type >=", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeLessThan(String value) {
            addCriterion("system_type <", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeLessThanOrEqualTo(String value) {
            addCriterion("system_type <=", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeLike(String value) {
            addCriterion("system_type like", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeNotLike(String value) {
            addCriterion("system_type not like", value, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeIn(List<String> values) {
            addCriterion("system_type in", values, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeNotIn(List<String> values) {
            addCriterion("system_type not in", values, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeBetween(String value1, String value2) {
            addCriterion("system_type between", value1, value2, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemTypeNotBetween(String value1, String value2) {
            addCriterion("system_type not between", value1, value2, "systemType");
            return (Criteria) this;
        }

        public Criteria andSystemDescIsNull() {
            addCriterion("system_desc is null");
            return (Criteria) this;
        }

        public Criteria andSystemDescIsNotNull() {
            addCriterion("system_desc is not null");
            return (Criteria) this;
        }

        public Criteria andSystemDescEqualTo(String value) {
            addCriterion("system_desc =", value, "systemDesc");
            return (Criteria) this;
        }

        public Criteria andSystemDescNotEqualTo(String value) {
            addCriterion("system_desc <>", value, "systemDesc");
            return (Criteria) this;
        }

        public Criteria andSystemDescGreaterThan(String value) {
            addCriterion("system_desc >", value, "systemDesc");
            return (Criteria) this;
        }

        public Criteria andSystemDescGreaterThanOrEqualTo(String value) {
            addCriterion("system_desc >=", value, "systemDesc");
            return (Criteria) this;
        }

        public Criteria andSystemDescLessThan(String value) {
            addCriterion("system_desc <", value, "systemDesc");
            return (Criteria) this;
        }

        public Criteria andSystemDescLessThanOrEqualTo(String value) {
            addCriterion("system_desc <=", value, "systemDesc");
            return (Criteria) this;
        }

        public Criteria andSystemDescLike(String value) {
            addCriterion("system_desc like", value, "systemDesc");
            return (Criteria) this;
        }

        public Criteria andSystemDescNotLike(String value) {
            addCriterion("system_desc not like", value, "systemDesc");
            return (Criteria) this;
        }

        public Criteria andSystemDescIn(List<String> values) {
            addCriterion("system_desc in", values, "systemDesc");
            return (Criteria) this;
        }

        public Criteria andSystemDescNotIn(List<String> values) {
            addCriterion("system_desc not in", values, "systemDesc");
            return (Criteria) this;
        }

        public Criteria andSystemDescBetween(String value1, String value2) {
            addCriterion("system_desc between", value1, value2, "systemDesc");
            return (Criteria) this;
        }

        public Criteria andSystemDescNotBetween(String value1, String value2) {
            addCriterion("system_desc not between", value1, value2, "systemDesc");
            return (Criteria) this;
        }

        public Criteria andSystemProvinceIsNull() {
            addCriterion("system_province is null");
            return (Criteria) this;
        }

        public Criteria andSystemProvinceIsNotNull() {
            addCriterion("system_province is not null");
            return (Criteria) this;
        }

        public Criteria andSystemProvinceEqualTo(String value) {
            addCriterion("system_province =", value, "systemProvince");
            return (Criteria) this;
        }

        public Criteria andSystemProvinceNotEqualTo(String value) {
            addCriterion("system_province <>", value, "systemProvince");
            return (Criteria) this;
        }

        public Criteria andSystemProvinceGreaterThan(String value) {
            addCriterion("system_province >", value, "systemProvince");
            return (Criteria) this;
        }

        public Criteria andSystemProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("system_province >=", value, "systemProvince");
            return (Criteria) this;
        }

        public Criteria andSystemProvinceLessThan(String value) {
            addCriterion("system_province <", value, "systemProvince");
            return (Criteria) this;
        }

        public Criteria andSystemProvinceLessThanOrEqualTo(String value) {
            addCriterion("system_province <=", value, "systemProvince");
            return (Criteria) this;
        }

        public Criteria andSystemProvinceLike(String value) {
            addCriterion("system_province like", value, "systemProvince");
            return (Criteria) this;
        }

        public Criteria andSystemProvinceNotLike(String value) {
            addCriterion("system_province not like", value, "systemProvince");
            return (Criteria) this;
        }

        public Criteria andSystemProvinceIn(List<String> values) {
            addCriterion("system_province in", values, "systemProvince");
            return (Criteria) this;
        }

        public Criteria andSystemProvinceNotIn(List<String> values) {
            addCriterion("system_province not in", values, "systemProvince");
            return (Criteria) this;
        }

        public Criteria andSystemProvinceBetween(String value1, String value2) {
            addCriterion("system_province between", value1, value2, "systemProvince");
            return (Criteria) this;
        }

        public Criteria andSystemProvinceNotBetween(String value1, String value2) {
            addCriterion("system_province not between", value1, value2, "systemProvince");
            return (Criteria) this;
        }

        public Criteria andSystemKeyIsNull() {
            addCriterion("system_key is null");
            return (Criteria) this;
        }

        public Criteria andSystemKeyIsNotNull() {
            addCriterion("system_key is not null");
            return (Criteria) this;
        }

        public Criteria andSystemKeyEqualTo(String value) {
            addCriterion("system_key =", value, "systemKey");
            return (Criteria) this;
        }

        public Criteria andSystemKeyNotEqualTo(String value) {
            addCriterion("system_key <>", value, "systemKey");
            return (Criteria) this;
        }

        public Criteria andSystemKeyGreaterThan(String value) {
            addCriterion("system_key >", value, "systemKey");
            return (Criteria) this;
        }

        public Criteria andSystemKeyGreaterThanOrEqualTo(String value) {
            addCriterion("system_key >=", value, "systemKey");
            return (Criteria) this;
        }

        public Criteria andSystemKeyLessThan(String value) {
            addCriterion("system_key <", value, "systemKey");
            return (Criteria) this;
        }

        public Criteria andSystemKeyLessThanOrEqualTo(String value) {
            addCriterion("system_key <=", value, "systemKey");
            return (Criteria) this;
        }

        public Criteria andSystemKeyLike(String value) {
            addCriterion("system_key like", value, "systemKey");
            return (Criteria) this;
        }

        public Criteria andSystemKeyNotLike(String value) {
            addCriterion("system_key not like", value, "systemKey");
            return (Criteria) this;
        }

        public Criteria andSystemKeyIn(List<String> values) {
            addCriterion("system_key in", values, "systemKey");
            return (Criteria) this;
        }

        public Criteria andSystemKeyNotIn(List<String> values) {
            addCriterion("system_key not in", values, "systemKey");
            return (Criteria) this;
        }

        public Criteria andSystemKeyBetween(String value1, String value2) {
            addCriterion("system_key between", value1, value2, "systemKey");
            return (Criteria) this;
        }

        public Criteria andSystemKeyNotBetween(String value1, String value2) {
            addCriterion("system_key not between", value1, value2, "systemKey");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table platform_system_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}