package com.syou.emedia.server.model.system;

import java.util.Date;

public class PFSystem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_info.system_id
     *
     * @mbggenerated
     */
    private Integer systemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_info.system_name
     *
     * @mbggenerated
     */
    private String systemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_info.system_code
     *
     * @mbggenerated
     */
    private String systemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_info.system_level
     *
     * @mbggenerated
     */
    private String systemLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_info.system_type
     *
     * @mbggenerated
     */
    private String systemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_info.system_desc
     *
     * @mbggenerated
     */
    private String systemDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_info.system_province
     *
     * @mbggenerated
     */
    private String systemProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_info.system_key
     *
     * @mbggenerated
     */
    private String systemKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_info.system_id
     *
     * @return the value of platform_system_info.system_id
     *
     * @mbggenerated
     */
    public Integer getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_info.system_id
     *
     * @param systemId the value for platform_system_info.system_id
     *
     * @mbggenerated
     */
    public void setSystemId(Integer systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_info.system_name
     *
     * @return the value of platform_system_info.system_name
     *
     * @mbggenerated
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_info.system_name
     *
     * @param systemName the value for platform_system_info.system_name
     *
     * @mbggenerated
     */
    public void setSystemName(String systemName) {
        this.systemName = systemName == null ? null : systemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_info.system_code
     *
     * @return the value of platform_system_info.system_code
     *
     * @mbggenerated
     */
    public String getSystemCode() {
        return systemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_info.system_code
     *
     * @param systemCode the value for platform_system_info.system_code
     *
     * @mbggenerated
     */
    public void setSystemCode(String systemCode) {
        this.systemCode = systemCode == null ? null : systemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_info.system_level
     *
     * @return the value of platform_system_info.system_level
     *
     * @mbggenerated
     */
    public String getSystemLevel() {
        return systemLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_info.system_level
     *
     * @param systemLevel the value for platform_system_info.system_level
     *
     * @mbggenerated
     */
    public void setSystemLevel(String systemLevel) {
        this.systemLevel = systemLevel == null ? null : systemLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_info.system_type
     *
     * @return the value of platform_system_info.system_type
     *
     * @mbggenerated
     */
    public String getSystemType() {
        return systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_info.system_type
     *
     * @param systemType the value for platform_system_info.system_type
     *
     * @mbggenerated
     */
    public void setSystemType(String systemType) {
        this.systemType = systemType == null ? null : systemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_info.system_desc
     *
     * @return the value of platform_system_info.system_desc
     *
     * @mbggenerated
     */
    public String getSystemDesc() {
        return systemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_info.system_desc
     *
     * @param systemDesc the value for platform_system_info.system_desc
     *
     * @mbggenerated
     */
    public void setSystemDesc(String systemDesc) {
        this.systemDesc = systemDesc == null ? null : systemDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_info.system_province
     *
     * @return the value of platform_system_info.system_province
     *
     * @mbggenerated
     */
    public String getSystemProvince() {
        return systemProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_info.system_province
     *
     * @param systemProvince the value for platform_system_info.system_province
     *
     * @mbggenerated
     */
    public void setSystemProvince(String systemProvince) {
        this.systemProvince = systemProvince == null ? null : systemProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_info.system_key
     *
     * @return the value of platform_system_info.system_key
     *
     * @mbggenerated
     */
    public String getSystemKey() {
        return systemKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_info.system_key
     *
     * @param systemKey the value for platform_system_info.system_key
     *
     * @mbggenerated
     */
    public void setSystemKey(String systemKey) {
        this.systemKey = systemKey == null ? null : systemKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_info.create_time
     *
     * @return the value of platform_system_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_info.create_time
     *
     * @param createTime the value for platform_system_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", systemId=").append(systemId);
        sb.append(", systemName=").append(systemName);
        sb.append(", systemCode=").append(systemCode);
        sb.append(", systemLevel=").append(systemLevel);
        sb.append(", systemType=").append(systemType);
        sb.append(", systemDesc=").append(systemDesc);
        sb.append(", systemProvince=").append(systemProvince);
        sb.append(", systemKey=").append(systemKey);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}