package com.syou.emedia.server.mapper.log;

import com.syou.emedia.server.model.log.PFLog;
import com.syou.emedia.server.model.log.PFLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PFLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    int countByExample(PFLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    int deleteByExample(PFLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    int insert(PFLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    int insertSelective(PFLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    List<PFLog> selectByExampleWithRowbounds(PFLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    List<PFLog> selectByExample(PFLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    PFLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PFLog record, @Param("example") PFLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PFLog record, @Param("example") PFLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PFLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PFLog record);
}