package com.syou.emedia.server.mapper.client;

import com.syou.emedia.server.model.client.PFClient;
import com.syou.emedia.server.model.client.PFClientExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PFClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_client
     *
     * @mbggenerated
     */
    int countByExample(PFClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_client
     *
     * @mbggenerated
     */
    int deleteByExample(PFClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_client
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_client
     *
     * @mbggenerated
     */
    int insert(PFClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_client
     *
     * @mbggenerated
     */
    int insertSelective(PFClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_client
     *
     * @mbggenerated
     */
    List<PFClient> selectByExampleWithRowbounds(PFClientExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_client
     *
     * @mbggenerated
     */
    List<PFClient> selectByExample(PFClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_client
     *
     * @mbggenerated
     */
    PFClient selectByPrimaryKey(Integer clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_client
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PFClient record, @Param("example") PFClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_client
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PFClient record, @Param("example") PFClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_client
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PFClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_client
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PFClient record);
}