package com.syou.emedia.server.mapper.sync;

import com.syou.emedia.server.model.sync.PFSyncAppInfoHis;
import com.syou.emedia.server.model.sync.PFSyncAppInfoHisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PFSyncAppInfoHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sync_appinfo_his
     *
     * @mbggenerated
     */
    int countByExample(PFSyncAppInfoHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sync_appinfo_his
     *
     * @mbggenerated
     */
    int deleteByExample(PFSyncAppInfoHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sync_appinfo_his
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer hisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sync_appinfo_his
     *
     * @mbggenerated
     */
    int insert(PFSyncAppInfoHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sync_appinfo_his
     *
     * @mbggenerated
     */
    int insertSelective(PFSyncAppInfoHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sync_appinfo_his
     *
     * @mbggenerated
     */
    List<PFSyncAppInfoHis> selectByExampleWithRowbounds(PFSyncAppInfoHisExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sync_appinfo_his
     *
     * @mbggenerated
     */
    List<PFSyncAppInfoHis> selectByExample(PFSyncAppInfoHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sync_appinfo_his
     *
     * @mbggenerated
     */
    PFSyncAppInfoHis selectByPrimaryKey(Integer hisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sync_appinfo_his
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PFSyncAppInfoHis record, @Param("example") PFSyncAppInfoHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sync_appinfo_his
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PFSyncAppInfoHis record, @Param("example") PFSyncAppInfoHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sync_appinfo_his
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PFSyncAppInfoHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sync_appinfo_his
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PFSyncAppInfoHis record);
}