package com.syou.emedia.server.model.attr;

import java.util.Date;

public class PFAttr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_attr.attr_id
     *
     * @mbggenerated
     */
    private Integer attrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_attr.attr_spec
     *
     * @mbggenerated
     */
    private String attrSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_attr.attr_name
     *
     * @mbggenerated
     */
    private String attrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_attr.attr_code
     *
     * @mbggenerated
     */
    private String attrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_attr.attr_value
     *
     * @mbggenerated
     */
    private String attrValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_attr.attr_type
     *
     * @mbggenerated
     */
    private String attrType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_attr.sys_code
     *
     * @mbggenerated
     */
    private String sysCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_system_attr.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_attr.attr_id
     *
     * @return the value of platform_system_attr.attr_id
     *
     * @mbggenerated
     */
    public Integer getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_attr.attr_id
     *
     * @param attrId the value for platform_system_attr.attr_id
     *
     * @mbggenerated
     */
    public void setAttrId(Integer attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_attr.attr_spec
     *
     * @return the value of platform_system_attr.attr_spec
     *
     * @mbggenerated
     */
    public String getAttrSpec() {
        return attrSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_attr.attr_spec
     *
     * @param attrSpec the value for platform_system_attr.attr_spec
     *
     * @mbggenerated
     */
    public void setAttrSpec(String attrSpec) {
        this.attrSpec = attrSpec == null ? null : attrSpec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_attr.attr_name
     *
     * @return the value of platform_system_attr.attr_name
     *
     * @mbggenerated
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_attr.attr_name
     *
     * @param attrName the value for platform_system_attr.attr_name
     *
     * @mbggenerated
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName == null ? null : attrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_attr.attr_code
     *
     * @return the value of platform_system_attr.attr_code
     *
     * @mbggenerated
     */
    public String getAttrCode() {
        return attrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_attr.attr_code
     *
     * @param attrCode the value for platform_system_attr.attr_code
     *
     * @mbggenerated
     */
    public void setAttrCode(String attrCode) {
        this.attrCode = attrCode == null ? null : attrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_attr.attr_value
     *
     * @return the value of platform_system_attr.attr_value
     *
     * @mbggenerated
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_attr.attr_value
     *
     * @param attrValue the value for platform_system_attr.attr_value
     *
     * @mbggenerated
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue == null ? null : attrValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_attr.attr_type
     *
     * @return the value of platform_system_attr.attr_type
     *
     * @mbggenerated
     */
    public String getAttrType() {
        return attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_attr.attr_type
     *
     * @param attrType the value for platform_system_attr.attr_type
     *
     * @mbggenerated
     */
    public void setAttrType(String attrType) {
        this.attrType = attrType == null ? null : attrType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_attr.sys_code
     *
     * @return the value of platform_system_attr.sys_code
     *
     * @mbggenerated
     */
    public String getSysCode() {
        return sysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_attr.sys_code
     *
     * @param sysCode the value for platform_system_attr.sys_code
     *
     * @mbggenerated
     */
    public void setSysCode(String sysCode) {
        this.sysCode = sysCode == null ? null : sysCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_system_attr.create_time
     *
     * @return the value of platform_system_attr.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_system_attr.create_time
     *
     * @param createTime the value for platform_system_attr.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_system_attr
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", attrId=").append(attrId);
        sb.append(", attrSpec=").append(attrSpec);
        sb.append(", attrName=").append(attrName);
        sb.append(", attrCode=").append(attrCode);
        sb.append(", attrValue=").append(attrValue);
        sb.append(", attrType=").append(attrType);
        sb.append(", sysCode=").append(sysCode);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}