package com.syou.emedia.server.mapper.qrcode;

import com.syou.emedia.server.model.qrcode.PFAppDownload;
import com.syou.emedia.server.model.qrcode.PFAppDownloadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PFAppDownloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_download
     *
     * @mbggenerated
     */
    int countByExample(PFAppDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_download
     *
     * @mbggenerated
     */
    int deleteByExample(PFAppDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_download
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer downloadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_download
     *
     * @mbggenerated
     */
    int insert(PFAppDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_download
     *
     * @mbggenerated
     */
    int insertSelective(PFAppDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_download
     *
     * @mbggenerated
     */
    List<PFAppDownload> selectByExampleWithRowbounds(PFAppDownloadExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_download
     *
     * @mbggenerated
     */
    List<PFAppDownload> selectByExample(PFAppDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_download
     *
     * @mbggenerated
     */
    PFAppDownload selectByPrimaryKey(Integer downloadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_download
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PFAppDownload record, @Param("example") PFAppDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_download
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PFAppDownload record, @Param("example") PFAppDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_download
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PFAppDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_app_download
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PFAppDownload record);
}