package com.syou.emedia.server.mapper.qrcode;

import com.syou.emedia.server.model.qrcode.PFQrcode;
import com.syou.emedia.server.model.qrcode.PFQrcodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PFQrcodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_qrcode
     *
     * @mbggenerated
     */
    int countByExample(PFQrcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_qrcode
     *
     * @mbggenerated
     */
    int deleteByExample(PFQrcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_qrcode
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer qrCodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_qrcode
     *
     * @mbggenerated
     */
    int insert(PFQrcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_qrcode
     *
     * @mbggenerated
     */
    int insertSelective(PFQrcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_qrcode
     *
     * @mbggenerated
     */
    List<PFQrcode> selectByExampleWithRowbounds(PFQrcodeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_qrcode
     *
     * @mbggenerated
     */
    List<PFQrcode> selectByExample(PFQrcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_qrcode
     *
     * @mbggenerated
     */
    PFQrcode selectByPrimaryKey(Integer qrCodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_qrcode
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PFQrcode record, @Param("example") PFQrcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_qrcode
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PFQrcode record, @Param("example") PFQrcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_qrcode
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PFQrcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_qrcode
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PFQrcode record);
}